### PR TITLE
Krupa's Exercise

### PR DESCRIPTION
**Pull request by KrupaPatel02**

### CODE REVIEW

**Comment by benjaminboruff** [comment]
Good work @KrupaPatel02 ! Now start in on the js/jQuery!

**Comment by benjaminboruff** [comment]
You can keep working on this same branch. Just remember to commit your changes to the local branch, then push it up. If you keep working on the `exerc-js` branch (keep making more and more commits on it, pushing your changes) it will "automatically" be updated in this PR so we can look at it as you go.

**Comment by benjaminboruff** [comment]
Just checking in ... looks like you've made some headway! I can see the data in the console and in the page. 
How is it going? Any questions?

**Comment by KrupaPatel02** [comment]
Yeah, I'm having little issue with loading the table, as I think it is returning me the whole list of characters and not the only that is related to film, so I'm trying to figure that out

**Comment by KrupaPatel02** [comment]
I think I'm up with all the required sections in the exercise except with QUnit which I haven't worked yet with, let me know if I'm missing out something.

**Comment by benjaminboruff** [comment]
Cool! Looking better. Looks like the list of films is not sorted in order
of release date, yet. That should be fixed. Also, when I hover over each
film in the dropdown, the mouse pointer should turn into the "hand/pointer"
cursor.

And, yes, I had never used qunit either when I did this exercise. Certainly
a bit of a learning curve, but do try to write a few tests, even if they
are only the "node" (non-browser) tests. (The qunit tests can be run via
command line or in the browser as "graphical" tests.) Try to write a few!

-Ben

-------------------------------------------------
{
  "name": "Benjamin Boruff",
  "title": "Developer",
  "url": "http:// <http://benjaminboruff.github.io/>boruff.me",
  "email": "ben <benboruff@gmail.com>@boruff.me"
}

**Comment by benjaminboruff** [comment]
Oh, man ... I sent that via email  instead of here. Sorry! Sheesh.

**Comment by KrupaPatel02** [comment]
I fixed 'hand/pointer' cursor issue, and for the order of films according to the release date, the order should be as following:

1.  A New Hope:                           1977-05-25
2. The Empire Strikes Back:       1980-05-17
3. Return of Jedi:                         1983-05-25
4. The Phantom Menace:           1999-05-19
5. Attack of the Clones:              2002-05-16
6. Revenge of the Smith:            2005-05-19
7.  The Force Awakens:               2015-12-11

I get the list as mentioned above in dropdown list if it is different from this than let me know.
And I'm trying to write the test codes for Qunit. If I find any queries will contact you.

**Comment by KrupaPatel02** [comment]
Hi Ben, I'm trying to run main-test.js on a terminal, so do I run by setting the path to js file or to the main index.html page.

**Comment by benjaminboruff** [comment]
To run `QUnit` from the terminal, you should install it via `npm` as per the instructions at `https://qunitjs.com/` , then then you run `qunit` in the root of your exercise dir, it should run all the `test/*.js` files (as tests) by default. Does that make sense? :)

**Comment by KrupaPatel02** [comment]
Yeah, I did install it via "npm", and it works on js file from the root dir "test/*.js".
Just was wondering as we have given file path in index.html so thought if it needs to be run from the same page. 
Although, got clear. 
Thanks

**Comment by benjaminboruff** [comment]
Yeah, there are two ways to run `QUnit` tests - in a terminal or in a browser tab so that it's "graphical". The instructions aren't really clear on that, but really, any testing is fine.

**Comment by benjaminboruff** [comment]
Looks like we are winding things down, so if you could go ahead and commit/push *any* test at all to this branch. We'll take a look!

**Comment by benjaminboruff** [comment]
What's your schedule like next week? Would you be available sometime next week to come in and have another meeting at Cowork?

**Comment by KrupaPatel02** [comment]
Yeah, I'm available for next week, let me know the day and time and will be there.
I'm still working on qunit test, will push it by tonight, is that ok?

**Comment by benjaminboruff** [comment]
Cool! How about Tues 5/22 (This coming Tues) 2pm? We're flexible!

**Comment by KrupaPatel02** [comment]
It works!
Will be there by 2 pm.

**Comment by benjaminboruff** [comment]
Excellent. You should have received an invite/meeting request from Simon using gmail/calendar. Let me know if you have not! If you already have, I think there is an "accept" button, or something ... so "Accept" if/when you get it! Thanks!

**Comment by KrupaPatel02** [comment]
Yes, I did receive the invite and accepted it, see you all tomorrow.
Have a great day ahead!

**Pull request closed without merging**
