### PR TITLE
Shweta js

### PR DESCRIPTION
**Pull request by kulsv**

### CODE REVIEW

**Comment by benjaminboruff** [comment]
Looking good! Looks like maybe a try at a few `qUnit` tests is all that remains? That's what the `test/main-test.js` is for. I think that's where you were writing a server ... 

So, I know there is a lerning curve on the `gUnit` tests, but try a few. Even i they are the non-browser type. The `qUnit` tests can be run/displayed in the browser OR via the command line using `node`. I don't care which, but give a try!
-Ben

**Comment by benjaminboruff** [comment]
We are starting to mind things down, so if you could go ahead and commit/push *any* test at all, we'll take a look at it!

**Comment by kulsv** [comment]
Hi Ben,

I am sorry. I missed this email.
I have uploaded the screenshot for one junit not test I performed on
Github. Do you want me to perform some more tests?

Thanks,
Shweta

**Comment by benjaminboruff** [comment]
Ok, how about just write **ANY** test in a file in the `test` dir, just so we can see it/run it ourselves.

Also, would you be available sometime next week for another interview/meeting here at Cowork? What's your schedule like next week?

**Comment by kulsv** [comment]
Hi Ben,

Yes I will upload the test files very soon and let you know.

I am available on Monday and Tuesday afternoon (preferably 2 p.m. or later).
Please let me know if this does not work for you. I will make myself
available accordingly.

Thank you.
Shweta

**Comment by hubpuller** [comment]
Shweta, if you have not already take a look at this article as well which discusses QUnit and why unit tests are a good idea.
https://qunitjs.com/intro/

**Comment by benjaminboruff** [comment]
How about Monday at 3pm at Cowork? Will that work?

**Pull request closed without merging**
